CREATE TABLE users(
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(40)  NOT NULL,
  LOGIN VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  BIRTH_DATE DATE,
  PHOTO BLOB,
  UNIQUE (FIRST_NAME,LAST_NAME),
  UNIQUE (LOGIN),
  UNIQUE (EMAIL),
  PRIMARY KEY(ID)
  );


CREATE TABLE message(
  ID INT NOT NULL AUTO_INCREMENT,
  USER_ID INT NOT NULL,
  MESSAGE VARCHAR(3000)  NOT NULL,
  MESSAGE_DATE_TIME  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (USER_ID) REFERENCES user(ID),
  PRIMARY KEY(ID)
);


CREATE TABLE role(
  ROLE_ID VARCHAR(30)  NOT NULL,
  PRIMARY KEY(ROLE_ID)
);

CREATE TABLE user_role_detail(
  USER_ID INT NOT NULL,
  ROLE_ID VARCHAR(30)  NOT NULL,
  PRIMARY KEY (USER_ID,ROLE_ID),
  CONSTRAINT FK_USER_ROLE_DETAIL_1 FOREIGN KEY (USER_ID)
  REFERENCES users (ID) ON DELETE CASCADE,
  CONSTRAINT FK_USER_ROLE_DETAIL_2 FOREIGN KEY (ROLE_ID)
  REFERENCES role (ROLE_ID)
);